# Generated by Django 5.1.4 on 2026-06-19 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('transfer_type', models.CharField(choices=[('TRASPASO', 'Traspaso'), ('PRESTAMO', 'Préstamo'), ('DEVOLUCION', 'Devolución')], default='TRASPASO', max_length=50)),
                ('status', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('DEVUELTO', 'Devuelto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('dispatch_guide_number', models.CharField(blank=True, max_length=100, null=True)),
                ('internal_guide_number', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_stock_transfers', to='organizations.branch')),
                ('origin_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_stock_transfers', to='organizations.branch')),
                ('parent_transfer', models.ForeignKey(blank=True, help_text='Se usa cuando este registro es devolución de un préstamo anterior.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_transfers', to='transfers.stocktransfer')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_stock_transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transfer',
                'verbose_name_plural': 'Stock Transfers',
                'db_table': 'stock_transfers',
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('approved_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('sent_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('returned_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('comments', models.TextField(blank=True, null=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transfer_items', to='inventory.inventorylot')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfer_items', to='products.product')),
                ('stock_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transfers.stocktransfer')),
            ],
            options={
                'verbose_name': 'Stock Transfer Item',
                'verbose_name_plural': 'Stock Transfer Items',
                'db_table': 'stock_transfer_items',
            },
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['origin_branch'], name='idx_transfer_origin'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['destination_branch'], name='idx_transfer_destination'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status'], name='idx_transfer_status'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['transfer_type'], name='idx_transfer_type'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('origin_branch', models.F('destination_branch')), _negated=True), name='chk_transfer_different_branches'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='chk_transfer_requested_positive'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.CheckConstraint(condition=models.Q(('sent_quantity__gte', 0)), name='chk_transfer_sent_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='chk_transfer_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferitem',
            constraint=models.CheckConstraint(condition=models.Q(('returned_quantity__gte', 0)), name='chk_transfer_returned_non_negative'),
        ),
    ]
