# Generated by Django 5.1.4 on 2026-06-19 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('products', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('VALIDADA', 'Validada'), ('OBSERVADA', 'Observada'), ('PARCIALMENTE_PAGADA', 'Parcialmente pagada'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='RECIBIDA', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='organizations.branch')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='organizations.costcenter')),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='organizations.legalentity')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Supplier Invoice',
                'verbose_name_plural': 'Supplier Invoices',
                'db_table': 'supplier_invoices',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('payment_method', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=50)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=50)),
                ('check_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('legal_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='organizations.legalentity')),
                ('supplier_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.supplierinvoice')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_year', models.IntegerField()),
                ('period_month', models.IntegerField()),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organizations.branch')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='products.productcategory')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organizations.costcenter')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organizations.legalentity')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'db_table': 'budgets',
                'indexes': [models.Index(fields=['legal_entity'], name='idx_budget_legal_entity'), models.Index(fields=['branch'], name='idx_budget_branch'), models.Index(fields=['period_year', 'period_month'], name='idx_budget_period')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_month__gte', 1), ('period_month__lte', 12)), name='chk_budget_month'), models.CheckConstraint(condition=models.Q(('budget_amount__gte', 0)), name='chk_budget_amount_non_negative'), models.CheckConstraint(condition=models.Q(('consumed_amount__gte', 0)), name='chk_budget_consumed_non_negative'), models.UniqueConstraint(fields=('legal_entity', 'branch', 'cost_center', 'category', 'period_year', 'period_month'), name='uq_budget_scope')],
            },
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier'], name='idx_invoice_supplier'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['legal_entity'], name='idx_invoice_legal_entity'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['branch'], name='idx_invoice_branch'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['status'], name='idx_invoice_status'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['invoice_number'], name='idx_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'invoice_number'), name='uq_supplier_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='chk_invoice_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='chk_invoice_tax_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='chk_invoice_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['supplier_invoice'], name='idx_payment_invoice'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['legal_entity'], name='idx_payment_legal_entity'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='idx_payment_status'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='idx_payment_date'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='chk_payment_amount_positive'),
        ),
    ]
