# Generated by Django 5.2.15 on 2026-07-20 15:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=180)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=180, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_days', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('supplier_sku', models.CharField(blank=True, max_length=100, null=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('price_valid_from', models.DateField(blank=True, null=True)),
                ('price_valid_to', models.DateField(blank=True, null=True)),
                ('min_purchase_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('requires_purchase_order', models.BooleanField(default=False)),
                ('allows_credit', models.BooleanField(default=True)),
                ('allows_cash_purchase', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_products', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'supplier_products',
            },
        ),
        migrations.CreateModel(
            name='SupplierProductPrice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='suppliers.supplierproduct')),
            ],
            options={
                'db_table': 'supplier_product_prices',
            },
        ),
        migrations.AddConstraint(
            model_name='supplierproduct',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='uq_supplier_product'),
        ),
        migrations.CreateModel(
            name='SupplierProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(default='CLP', max_length=10)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('previous_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('change_reason', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('MANUAL', 'Actualización manual'), ('PURCHASE', 'Orden de compra'), ('IMPORT', 'Importación'), ('INITIAL', 'Precio inicial')], default='MANUAL', max_length=30)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_price_changes', to=settings.AUTH_USER_MODEL)),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_history', to='suppliers.supplierproduct')),
            ],
            options={
                'db_table': 'supplier_product_price_history',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['supplier_product', 'effective_date'], name='supplier_pr_supplie_ef084b_idx')],
            },
        ),
    ]
