# Generated by Django 5.2.15 on 2026-07-20 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationForm',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_type', models.CharField(choices=[('ALL', 'Todos los usuarios'), ('BRANCH', 'Sucursal específica'), ('ROLE', 'Rol específico')], default='ALL', max_length=20)),
                ('days_to_complete', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_forms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evaluation Form',
                'verbose_name_plural': 'Evaluation Forms',
                'db_table': 'evaluation_forms',
            },
        ),
        migrations.CreateModel(
            name='EvaluationFormQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('TEXT', 'Texto libre'), ('RATING', 'Puntuación (1–N)'), ('MULTIPLE', 'Selección múltiple'), ('SINGLE', 'Selección única'), ('BOOLEAN', 'Sí / No'), ('DATE', 'Fecha')], default='TEXT', max_length=20)),
                ('rating_max', models.PositiveIntegerField(blank=True, default=5, null=True)),
                ('options', models.JSONField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('helper_text', models.CharField(blank=True, max_length=300, null=True)),
                ('evaluation_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluationform')),
            ],
            options={
                'verbose_name': 'Evaluation Form Question',
                'verbose_name_plural': 'Evaluation Form Questions',
                'db_table': 'evaluation_form_questions',
                'ordering': ['evaluation_form', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserEvaluation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('EXPIRED', 'Vencida')], default='PENDING', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='WEB', max_length=50)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluations', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_evaluations', to='organizations.branch')),
                ('evaluated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('evaluation_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_evaluations', to='evaluations.evaluationform')),
            ],
            options={
                'verbose_name': 'User Evaluation',
                'verbose_name_plural': 'User Evaluations',
                'db_table': 'user_evaluations',
            },
        ),
        migrations.CreateModel(
            name='UserEvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('answer_text', models.TextField(blank=True, null=True)),
                ('answer_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('answer_options', models.JSONField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='evaluations.evaluationformquestion')),
                ('user_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.userevaluation')),
            ],
            options={
                'verbose_name': 'User Evaluation Answer',
                'verbose_name_plural': 'User Evaluation Answers',
                'db_table': 'user_evaluation_answers',
            },
        ),
        migrations.AddIndex(
            model_name='evaluationform',
            index=models.Index(fields=['is_active'], name='idx_eval_form_active'),
        ),
        migrations.AddIndex(
            model_name='evaluationform',
            index=models.Index(fields=['created_at'], name='idx_eval_form_created'),
        ),
        migrations.AddConstraint(
            model_name='evaluationformquestion',
            constraint=models.UniqueConstraint(fields=('evaluation_form', 'order'), name='uq_eval_question_order'),
        ),
        migrations.AddIndex(
            model_name='userevaluation',
            index=models.Index(fields=['evaluation_form'], name='idx_ueval_form'),
        ),
        migrations.AddIndex(
            model_name='userevaluation',
            index=models.Index(fields=['evaluated_user'], name='idx_ueval_user'),
        ),
        migrations.AddIndex(
            model_name='userevaluation',
            index=models.Index(fields=['status'], name='idx_ueval_status'),
        ),
        migrations.AddIndex(
            model_name='userevaluation',
            index=models.Index(fields=['due_date'], name='idx_ueval_due_date'),
        ),
        migrations.AddConstraint(
            model_name='userevaluationanswer',
            constraint=models.UniqueConstraint(fields=('user_evaluation', 'question'), name='uq_ueval_answer'),
        ),
        migrations.RemoveField(
            model_name='evaluationform',
            name='days_to_complete',
        ),
    ]
