# Generated by Django 5.2.15 on 2026-07-23 03:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationform',
            name='google_form_edit_url',
            field=models.URLField(blank=True, help_text='Enlace de edición del formulario en Google Forms.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='google_form_id',
            field=models.CharField(blank=True, help_text='Identificador del formulario generado por Google Forms.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='google_form_url',
            field=models.URLField(blank=True, help_text='Enlace público para responder el formulario.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='google_last_response_sync_at',
            field=models.DateTimeField(blank=True, help_text='Fecha de la última consulta de respuestas en Google Forms.', null=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='google_sync_error',
            field=models.TextField(blank=True, help_text='Detalle del último error de sincronización.', null=True),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='google_sync_status',
            field=models.CharField(choices=[('NOT_SYNCED', 'No sincronizado'), ('SYNCING', 'Sincronizando'), ('SYNCED', 'Sincronizado'), ('ERROR', 'Error')], default='NOT_SYNCED', max_length=20),
        ),
        migrations.AddField(
            model_name='evaluationform',
            name='google_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evaluationformquestion',
            name='google_item_id',
            field=models.CharField(blank=True, help_text='ID del ítem asignado por Google Forms.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evaluationformquestion',
            name='google_question_id',
            field=models.CharField(blank=True, help_text='ID usado por Google para identificar las respuestas.', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='evaluationform',
            index=models.Index(fields=['google_sync_status'], name='idx_eval_google_status'),
        ),
        migrations.AddIndex(
            model_name='evaluationformquestion',
            index=models.Index(fields=['evaluation_form', 'order'], name='idx_eval_question_form_order'),
        ),
        migrations.AddIndex(
            model_name='evaluationformquestion',
            index=models.Index(fields=['google_question_id'], name='idx_eval_google_question'),
        ),
    ]
