# Generated by Django 5.1.4 on 2026-06-19 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', 'Éxito'), ('STOCK_BAJO', 'Stock bajo'), ('STOCK_VENCIDO', 'Stock vencido'), ('SOLICITUD_INSUMOS', 'Solicitud de insumos'), ('ORDEN_COMPRA', 'Orden de compra'), ('TRASPASO', 'Traspaso'), ('RECLAMO_PROVEEDOR', 'Reclamo proveedor'), ('PAGO', 'Pago'), ('SISTEMA', 'Sistema')], default='INFO', max_length=80)),
                ('related_app', models.CharField(blank=True, max_length=80, null=True)),
                ('related_model', models.CharField(blank=True, max_length=80, null=True)),
                ('related_uuid', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_notif_user_read'), models.Index(fields=['notification_type'], name='idx_notif_type'), models.Index(fields=['related_model', 'related_uuid'], name='idx_notif_related'), models.Index(fields=['created_at'], name='idx_notif_created_at')],
            },
        ),
    ]
